### ISSUE TITLE
tracking modularization of clm40 isotopes

### ISSUE THREAD

**Issue by mvertens** [CESM-Development/water-isotopes#3]
# new module

HydrologyTracer.F90 - **in progress - mv**
# biogeophys

BalanceCheckMod.F90 - bja **in progress - needs to be subroutinized**
BareGroundFluxesMod.F90 - **DONE**
Biogeophysics1Mod.F90 - **DONE**
Biogeophysics2Mod.F90 - **DONE**
BiogeophysicsLakeMod.F90 - **DONE**
BiogeophysRestMod.F90 - **will not be subroutinized - only use pointers to new data type**
CanopyFluxesMod.F90 - **DONE (does result in non-bfb changes)**
clm_driverInitMod.F90 - **DONE**
Hydrology1Mod.F90 - **DONE**
Hydrology2Mod.F90 - **DONE**
HydrologyLakeMod.F90 - **DONE**
SnowHydrologyMod.F90 - **in progress (mostly done) - needs to be subroutinized**
SoilHydrologyMod.F90 - **DONE**
SoilTemperatureMod.F90 - **DONE**
SurfaceAlbedoMod.F90 - **DONE (did not need any water isotopes)**
UrbanInitMod.F90 - **DONE**
UrbanMod.F90 - **DONE**
# main

clm_atmlnd.F90
clm_driver.F90
clmtype.F90
clmtypeInitMod.F90
dynlandMod.F90
histFldsMod.F90
lnd_import_export.F90
mkarbinitMod.F90 - **in-progress - mv**
pft2colMod.F90
pftdynMod.F90

**Comment by bandre-ucar** [comment]
Baseline dir on yellowstone

clm4-wiso-a8f55

**Comment by bandre-ucar** [comment]
baseline dir on yellowstone:

clm4-wiso-009077d

**Comment by bandre-ucar** [comment]
Test directory: `clm4-wiso-b63b95a`
Includes cpl and clm baseline history files for:
`SMS.f10_f10.ICLM40WISO.yellowstone_intel.clm-40default`

**Comment by bandre-ucar** [comment]
This is essentially done. I believe the only outstanding issue is snow hydrology, which may need to be completely reimplemented but is replaced by betr, so we are punting on for now.
